# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'

  App\Service\CollectionHandler:
    arguments:
      $collections:
        fruit: '@App\Collection\FruitCollection'
        vegetable: '@App\Collection\VegetableCollection'

  App\Serializer\Normalizer\FoodItemNormalizer:
    arguments:
      $unitConversion: '@App\Service\UnitConversion'
      $objectNormalizer: '@serializer.normalizer.object'

  App\Serializer\Denormalizer\FoodItemDenormalizer:
    arguments:
      $unitConversion: '@App\Service\UnitConversion'

  file_locator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - '%kernel.project_dir%'

  App\Service\JsonFileReader:
    arguments:
      $fileLocator: '@file_locator'
